services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswrd
    ports:
      - "5432:5432" #всегда такой порт у бдышек(конкретный постгрес)

  wildfly:
    container_name: big-cringe
    hostname: localhost
    image: quay.io/wildfly/wildfly:28.0.0.Final-jdk17
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - JAVA_OPTS=-Djboss.bind.address=0.0.0.0
    volumes:
      - ./target/dependency/postgresql-42.7.4.jar:/opt/jboss/wildfly/modules/system/layers/base/org/postgresql/main/postgresql-42.7.4.jar
      - ./target/lab_4_jakartaEE-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/app.war
    extra_hosts:
      - "lil-star:192.168.31.233"
#    volumes:
#      - .nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./front/src:/usr/share/nginx